# Generated by Django 4.1 on 2022-08-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestorName', models.CharField(max_length=100)),
                ('requestorEmail', models.EmailField(max_length=254)),
                ('requestorTNum', models.CharField(max_length=30)),
                ('businessUnit', models.CharField(max_length=100)),
                ('plantCode', models.CharField(max_length=100)),
                ('requestName', models.CharField(max_length=100)),
                ('projectManager', models.CharField(max_length=100, null=True)),
                ('sapCode', models.CharField(max_length=30, null=True)),
                ('userID', models.CharField(max_length=100, null=True)),
                ('isHighPriority', models.BooleanField(default=False)),
                ('materialDescription', models.CharField(max_length=40)),
                ('unitOfMeasurement', models.CharField(max_length=5)),
                ('materialGroup', models.CharField(max_length=100)),
                ('manufacturerName', models.CharField(max_length=100)),
                ('materialPartNumber', models.CharField(max_length=100)),
                ('attachment', models.CharField(max_length=100)),
                ('isDocumented', models.BooleanField(default=False)),
                ('ibauNum', models.CharField(max_length=30, null=True)),
                ('ibauName', models.CharField(max_length=100, null=True)),
                ('functionalLocations', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='partOneImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100, null=True)),
                ('isHighPriority', models.BooleanField(default=False)),
                ('materialDescription', models.CharField(max_length=40)),
                ('unitOfMeasurement', models.CharField(max_length=5)),
                ('materialGroup', models.CharField(max_length=100)),
                ('manufacturerName', models.CharField(max_length=100)),
                ('materialPartNumber', models.CharField(max_length=100)),
                ('attachment', models.CharField(max_length=100)),
                ('isDocumented', models.BooleanField(default=False)),
                ('ibauNum', models.CharField(max_length=30, null=True)),
                ('ibauName', models.CharField(max_length=100, null=True)),
                ('functionalLocations', models.CharField(max_length=30)),
                ('vendorName', models.CharField(max_length=30, null=True)),
                ('vendorPartNum', models.CharField(max_length=30, null=True)),
                ('vendorPartNumRevision', models.CharField(max_length=2, null=True)),
                ('technicalContact', models.CharField(max_length=30, null=True)),
                ('security', models.CharField(max_length=30)),
                ('tcProjectId', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor', models.CharField(max_length=50)),
                ('testFile', models.FileField(null=True, upload_to='files/', verbose_name='')),
            ],
        ),
    ]
