# Generated by Django 4.1 on 2022-08-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='uploader',
        ),
    ]
