# Generated by Django 4.1 on 2022-08-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_1', '0002_remove_testmodel_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor', models.CharField(max_length=50)),
                ('testFile', models.FileField(upload_to='')),
            ],
        ),
    ]
