# Generated by Django 4.1 on 2022-08-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_1', '0002_alter_partoneimport_ishighpriority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partoneimport',
            name='isHighPriority',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partoneimport',
            name='security',
            field=models.BooleanField(default=False),
        ),
    ]
