# Generated by Django 4.1 on 2022-08-22 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_1', '0003_filemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileModel',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='requestor',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
