# Generated by Django 4.1 on 2022-08-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_1', '0005_alter_testmodel_testfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestorName', models.CharField(max_length=100)),
                ('requestorEmail', models.EmailField(max_length=254)),
                ('requestorTNum', models.CharField(max_length=30)),
                ('businessUnit', models.CharField(max_length=100)),
                ('plantCode', models.CharField(max_length=100)),
                ('requestName', models.CharField(max_length=100)),
                ('projectManager', models.CharField(blank=True, max_length=100)),
                ('sapCode', models.CharField(blank=True, max_length=30)),
                ('userID', models.CharField(blank=True, max_length=100)),
                ('isHighPriority', models.BooleanField(default=False)),
                ('materialDescription', models.CharField(max_length=40)),
                ('unitOfMeasurement', models.CharField(max_length=5)),
                ('materialGroup', models.CharField(max_length=100)),
                ('manufacturerName', models.CharField(max_length=100)),
                ('materialPartNumber', models.CharField(max_length=100)),
                ('attachment', models.CharField(max_length=100)),
                ('isDocumented', models.BooleanField(default=False)),
                ('ibauNum', models.CharField(blank=True, max_length=30)),
                ('ibauName', models.CharField(blank=True, max_length=100)),
                ('functionalLocations', models.CharField(max_length=30)),
            ],
        ),
    ]
