# Generated by Django 4.1 on 2022-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp_1', '0006_fileread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileread',
            name='ibauName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fileread',
            name='ibauNum',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fileread',
            name='projectManager',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fileread',
            name='sapCode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fileread',
            name='userID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
